media:
  input: public
  output: /
content:
  - name: posts
    label: Posts
    type: collection
    path: src/content/posts
    view:
      fields: [ title, draft, date ]
    fields:
      - { name: title, label: Title, type: string, required: true }
      - { name: description, label: Description, type: string }
      - { name: pubDatetime, label: Date, type: date }
      - { name: Image, label: image, type: image }
      - { name: categories, label: categories, type: string, list: true }
      - { name: authors, label: Authors, type: string }
      - { name: tags, label: Tags, type: string, list: true }
      - { name: draft, label: Draft, type: boolean }
      - { name: body, label: Body, type: rich-text }
  - name: authors
    label: Authors
    path: src/content/authors
    type: file
    fields: 
      - { name: layout, type: string, hidden: true, default: layouts/base.njk }
      - { name: title, label: Title, type: string }
      - { name: body, label: Body, type: rich-text, options: { input: public/assets, output: /assets } }
  - name: about
    label: About page
    type: file
    path: src/content/about/index.md
    fields:
      - { name: layout, type: string, hidden: true, default: layouts/base.njk }
      - { name: title, label: Title, type: string }
      - { name: body, label: Body, type: rich-text, options: { input: public/assets, output: /assets } }